# Generated by Django 3.1.6 on 2021-02-18 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(default='', max_length=200)),
                ('deadline', models.DateTimeField(null=True, verbose_name='deadline date')),
            ],
        ),
    ]
